version: "3.8"
services:
  client:
    build: ./client
    container_name: client
    ports:
      - 3000:3000
    networks:
      - workenv
  server:
    build: ./server
    container_name: server
    ports:
      - 4000:4000
    networks:
      - workenv

networks:
  workenv:
    name: local_development
